name: CI

# When workflow is triggered
on:
  push:
    branches: main
  workflow_dispatch:
    

# Jobs to carry out
jobs:
  deploy:
    # Operating system to run job on
    runs-on: ubuntu-latest
    # Steps in job
    steps:
      # Get code from repo
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Use Node.js 14.x
        uses: actions/setup-node@v3
        with:
          node-version: 14.x
      # Run npm install and build on our code
      - run: yarn install
      - run: yarn build
